ruby '2.5.1'

source 'https://rubygems.org'
gem 'activesupport', '4.1.4'
gem 'actionview'
gem 'oauth'
gem 'octokit'
gem 'pry'
gem 'smashing'
gem 'koala'
gem 'strava-api-v3'
gem 'steam-api'
gem 'wakatime'
gem 'rmagick'
gem 'httparty'
